### ISSUE TITLE
file encoding problem

### ISSUE THREAD

**Issue by RenJIa-J** [telosys-tools-bricks/telosys-tools-generator#1]
Hi,I'm chuck.I'm a coder in china.I use your team project TelosysTool generate Code,but some chinese words happen encoding problem.My project encoding is 'UTF-8',I want know how let it right?

I read a little source code,in the 'Generator.java'
`OutputStream out = new FileOutputStream(file);`
if change it 
`OutputStreamWriter out = new OutputStreamWriter(new FileOutputStream(file),"UTF-8");`
can make it right?
help me,please.

**Comment by l-gu** [comment]
Fixed
