### ISSUE TITLE
File encoding not UTF8 with Telosys generator

### ISSUE THREAD

**Issue by SinigagliaSteeve** [telosys-tools-bricks/telosys-tools-generator#2]
Hi,
I encountred some issues when i generated file.
e.g : I generate file with $today.date, my local is "FR", so the month is "Déc". However the month was encoding like : "Created on 22 d�c. 2016 ( Time 11:12:59 )", and maven won't compile this (force utf 8 compilation).

Thanks you.

**Comment by l-gu** [comment]
Fixed
