### ISSUE TITLE
unique values feature added to the model

### ISSUE THREAD

**Issue by franckleveque** [telosys-tools-bricks/telosys-tools-generator#6]
Hi,

It would be interesting to have access to a unique feature from the model in the same way we have currently access to .isNotBlank() , .isNotEmpty(), .isNotNull().

A more generic approach would be to add a features array to the model allowing people to add any type of informations they require.

**Comment by l-gu** [comment]
Hi, 
yes the "tags" (with '#' character)  will be added in a future version
eg  #mytag,  #myvalue(123),  etc

**Comment by l-gu** [comment]
Done : tags and @Unique annotation
